// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace DragonBones
{
		public class ArmatureData
		{
	
	      public string name;
		  public List<IAreaData> areaDataList;
		  public List<BoneData> boneDataList;
		  public List<SkinData> skinDataList;
		  public List<AnimationData> animationDataList;

		  static bool sortBone( KeyValuePair<int, BoneData> a, KeyValuePair<int, BoneData> b)
		  {
			return a.Key < b.Key;
		  }

		  public ArmatureData ()
		  {
		  }

		IAreaData getAreaData(string areaName) 
		{
			if (areaDataList.Count <= 0)
			{
				return null;
			}
			
			if (areaName.Length <= 0 )
			{
				return areaDataList[0];
			}
			
			for (int i = 0; i < areaDataList.Count; ++i)
			{
				if (areaDataList[i].name == areaName)
				{
					return areaDataList[i];
				}
			}
			
			return null;
		}
		
		BoneData getBoneData(string boneName) 
		{
			for (int i = 0; i < boneDataList.Count;  ++i)
			{
				if (boneDataList[i].name == boneName)
				{
					return boneDataList[i];
				}
			}
			
			return null;
		}
		
		SkinData getSkinData(string skinName)
		{
			if (skinDataList.Count<=0)
			{
				return null;
			}
			
			if (skinName.Count <= 0 )
			{
				return skinDataList[0];
			}
			
			for (int i = 0; i < skinDataList.Count;  ++i)
			{
				if (skinDataList[i].name == skinName)
				{
					return skinDataList[i];
				}
			}
			
			return null;
		}
		
		AnimationData getAnimationData(string animationName) 
		{
			for (int i = 0; i < animationDataList.Count;  ++i)
			{
				if (animationDataList[i].name == animationName)
				{
					return animationDataList[i];
				}
			}
			
			return null;
		}
		
		void sortBoneDataList()
		{
			if (boneDataList.Count)
			{
				return;
			}
			
			List<KeyValuePair<int , BoneData>> sortedList;
			
			for (int i = 0; i < boneDataList.Count; ++i)
			{
				BoneData boneData = boneDataList[i];
				BoneData parentData = boneData;
				int level = 0;
				
				while (parentData)
				{
					parentData = getBoneData(parentData.parent);
					level ++;
				}
				
				sortedList.Add(new KeyValuePair<int, BoneData>(level , boneData));
			}
			
			sortedList.Sort(sortBone);
			
			for (int i = 0; i < sortedList.Count; ++i)
			{
				boneDataList[i] = sortedList[i].Value;
			}
		}


		}
}

