// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Com.Viperstudio.Geom;
namespace DragonBones
{
		public class BoneData
		{

	
	    public bool inheritScale;
		public bool inheritRotation;
		public float length;
		
		public string name;
		public string parent;
		public Transform global;
		public Transform transform;
		public List<IAreaData> areaDataList;
		


				public BoneData ()
				{
				}

		IAreaData getAreaData(string areaName) 
		{
			if (areaDataList.Count <= 0)
			{
				return null;
			}
			
			if (areaName.Length)
			{
				return areaDataList[0];
			}
			
			for (int i = 0; i < areaDataList.Count; ++i)
			{
				if (areaDataList[i].name == areaName)
				{
					return areaDataList[i];
				}
			}
			
			return null;
		}


		}
}

