// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Com.Viperstudio.Geom;
namespace DragonBones
{
		public class TransformFrame
		{
	
		public bool visible;
		public bool tweenScale;
		public int tweenRotate;
		public int displayIndex;
		public float zOrder;
		// NaN:no tween, 10:auto tween, [-1, 0):ease in, 0:line easing, (0, 1]:ease out, (1, 2]:ease in out
		public float tweenEasing;

		public Transform global;
		public Transform transform;
		public Point pivot;
		public Point scaleOffset;
		public ColorTransform *color;


		public TransformFrame ()
		{
			visible = true;
			tweenScale = true;
			tweenRotate = 0;
			displayIndex = 0;
			zOrder = 0.f;
			tweenEasing = NO_TWEEN_EASING;
			frameType = FrameType.FT_TRANSFORM_FRAME;
			color = null;

	    }
		}
}

