// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Com.Viperstudio.Geom;
namespace DragonBones
{
		public class TransformTimeline
		{
	
		public bool transformed;
		public float offset;

		public string name;
		public Transform originTransform;
		public Point originPivot;

		public TransformTimeline ()
		{
			offset = 0.f;
			transformed = false;
		}


		}
}

