// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace DragonBones
{
		public class Animation
		{

		public enum AnimationFadeOutMode
		{
		    NONE, SAME_LAYER, SAME_GROUP, SAME_LAYER_AND_GROUP, ALL
		}

		     
		public bool autoTween;

		protected bool _isFading;
		protected bool _isPlaying;
		protected float _timeScale;

		protected List<string> _animationList;
		protected List<AnimationData> _animationDataList;
		protected List<AnimationState> _animationStateList;
		
		Armature *_armature;
		AnimationState *_lastAnimationState;


		public Animation ()
		{
		}

		public virtual List<string> getAnimationList()
		{
			
		}
		
		public virtual bool getIsPlaying()
		{
			
		}
		
		public virtual bool getIsComplete()
		{
			
		}
		
		public virtual AnimationState getLastAnimationState()
		{
			
		}
		
		public virtual float getTimeScale()
		{
			
		}
		
		public virtual void setTimeScale(float timeScale)
		{
			
			
		}
		
		public virtual List<AnimationData> getAnimationDataList()
		{
			
		}
		
		public virtual void getAnimationDataList(List<AnimationData> animationDataList)
		{
			
		}
		
		public virtual AnimationState gotoAndPlay( string animationName,
		                                          float fadeInTime = -1.f,
		                                          float duration = -1.f,
		                                          int playTimes = -1,
		                                          int layer = 0,
		                                          string group = "",
		                                          AnimationFadeOutMode fadeOutMode = AnimationFadeOutMode.SAME_LAYER_AND_GROUP,
		                                          bool pauseFadeOut = true,
		                                          bool pauseFadeIn = true
		                                          )
		{
			
		}
		
		public virtual AnimationState gotoAndStop(
			string animationName,
			float time,
			float normalizedTime = -1.f,
			float fadeInTime = 0.f,
			float duration = -1.f,
			int layer = 0,
			string group = "",
			AnimationFadeOutMode fadeOutMode = AnimationFadeOutMode.ALL
			)
		{
			
		}
		
		public virtual void play();
		public virtual void stop();
		public virtual void advanceTime(float passedTime);
		
		public virtual bool hasAnimation(string animationName);
		public virtual AnimationState* getState(string name, int layer = 0);

	    protected virtual void addState(AnimationState *animationState)
		{
		}

		protected	virtual void removeState(AnimationState *animationState);
		protected	virtual void updateAnimationStates();


		
}

