// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Com.Viperstudio.Geom;
namespace DragonBones
{
		public class TimelineState
		{

	
		private enum  UpdateState {UPDATE, UPDATE_ONCE, UNUPDATE};
		
		private  static List<TimelineState> _pool;
		private static TimelineState borrowObject();
		private static void returnObject(TimelineState timelineState);
		private static void clearObjects();
		
	
		public	string name;
		
	
		private 	bool _blendEnabled;
		private bool _isComplete;
		private bool _tweenTransform;
		private bool _tweenScale;
		private bool _tweenColor;
		private int _currentTime;
		private int _currentFrameIndex;
		private int _currentFramePosition;
		private int _currentFrameDuration;
		private int _totalTime;
		private float _weight;
		private float _tweenEasing;
		
		private UpdateState _updateState;
		private Transform _transform;
		private Transform _durationTransform;
		private Transform _originTransform;
		private Point _pivot;
		private Point _durationPivot;
		private Point _originPivot;
		private ColorTransform _durationColor;
		
		private Bone _bone;
		private AnimationState _animationState;
		private TransformTimeline _timeline;


		public TimelineState ()
		{
		}

	
		private 	void fadeIn(Bone bone, AnimationState animationState, TransformTimeline timeline);
		private void fadeOut();
		private void update(float progress);
		private void updateMultipleFrame(float progress);
		private void updateToNextFrame(int currentPlayTimes);
		private void updateTween();
		private void updateSingleFrame();
		private void clear();


		}
}

