// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace DragonBones
{
	public class WorldClock: IAnimatable
	{

	
		public	static WorldClock clock;
		
	
		private 	bool _dirty;
		private bool _isPlaying;
		private float _time;
		private float _timeScale;
		
		
		
		private  List<IAnimatable> _animatableList;

		public WorldClock ()
		{
		}

	
		public	static WorldClock getInstance();
		
		public float getTime() ;
		
		public float getTimeScale() ;
		public void setTimeScale(float timeScale);


		public virtual bool contains( IAnimatable animatable) ;
		public virtual void add(IAnimatable animatable);
		public virtual void remove(IAnimatable animatable);
		public virtual void removeAll();
		public virtual void play();
		public virtual void stop();
		public virtual void advanceTime(float passedTime);


   }
}

