// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Com.Viperstudio.Geom;

namespace DragonBones
{
		public class Bone
		{

	
	      private static bool sortState(TimelineState a,  TimelineState b);
		
	
		  public string displayController;
		
	
	protected	bool _isColorChanged;
	protected int _needUpdate;
		
		protected Point _tweenPivot;
		protected Transform _tween;
		protected List<Bone> _boneList;
		protected List<Slot> _slotList;
		protected List<TimelineState> _timelineStateList;


		public Bone ()
		{
		}

	
		public	virtual Slot getSlot() ;
		public	virtual  List<Slot> getSlots();
		public	virtual  List<Bone> getBones();
		
		public	virtual void setVisible(bool vislble) ;

		public	virtual void invalidUpdate();
		public	virtual bool contains( Object obj);
		public	virtual void addChild(Object obj);
		public	virtual void removeChild(Object obj);
		
	
		protected 	virtual void update(bool needUpdate);
		protected virtual void updateColor(
			int aOffset,
			int rOffset,
			int gOffset,
			int bOffset,
			float aMultiplier,
			float rMultiplier,
			float gMultiplier,
			float bMultiplier,
			bool colorChanged
			);
		protected virtual void hideSlots();
		protected virtual void arriveAtFrame(TransformFrame frame,  TimelineState timelineState, AnimationState animationState, bool isCross);
		protected virtual void addState(TimelineState timelineState);
		protected virtual void removeState(TimelineState timelineState);
		protected virtual void blendingTimeline();

	 
		protected	virtual void setArmature(Armature armature);




		}
}

