// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Com.Viperstudio.Geom;
namespace DragonBones
{
		public class Object
		{

	
		public	bool inheritRotation;
		public bool inheritScale;
		
		public string name;
		public Transform global;
		public Transform origin;
		public Transform offset;
		public Matrix globalTransformMatrix;
		
		public object userData;
		
	
	    protected	bool _visible;
		
		protected Armature _armature;
		protected Bone _parent;


		public Object ()
		{
		}

	
		public 	virtual bool getVisible();
		public virtual void setVisible(bool vislble);
		
		public virtual Armature getArmature();
		public virtual Bone getParent();
		
	
		protected 	virtual void setArmature(Armature armature);
		protected virtual void setParent(Bone bone);


		}
}

