// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace DragonBones
{
		public class Slot
		{

	
		protected 	bool _isShowDisplay;
		protected int _displayIndex;
		protected float _originZOrder;
		protected float _tweenZOrder;
		protected float _offsetZOrder;
		protected DragonBones.BlendMode _blendMode;
		
		// <displayOrArmature*, DisplayType>
		protected List<KeyValuePair<object, DisplayType>> _displayList;
		
		protected SlotData _slotData;
		protected object _display;
		protected Armature _childArmature;


				public Slot ()
				{
				}
		}
}

